### ISSUE TITLE
Data?

### ISSUE THREAD

**Issue by ddofer** [uci-cbcl/DanQ#1]
I'd like to try your model - but I have no idea what sort of format it expect the data to be in. Any chance you can upload a sample to the GitHub? 
Thanks.

**Comment by daquang** [comment]
Thank you for your interest in DanQ. Sorry for the delay, I've been traveling. Perhaps you can help me improve it. What exactly would you like to see? Right now, I have only made the training code available. If you want, I can write a script that will accept the weights from a fully trained model and output predictions from an input sample hdf5 file into an output hdf5 file.

**Comment by ddofer** [comment]
Just..raw data so I can run it, and to see how to format my own data for it

**Comment by daquang** [comment]
Sorry about that. I did not update the README properly. I will do that later tonight. You can download the original .mat files from DeepSEA: http://deepsea.princeton.edu/media/code/deepsea_train_bundle.v0.9.tar.gz

After you extract the contents, you can move the 3 .mat files into a folder called "data/" and run the training scripts.

**Comment by daquang** [comment]
Sorry about that. I did not update the README properly. I will do that later tonight. You can download the original .mat files from DeepSEA: http://deepsea.princeton.edu/media/code/deepsea_train_bundle.v0.9.tar.gz

After you extract the contents, you can move the 3 .mat files into a folder called "data/" and run the training scripts.

**Comment by n-long** [comment]
Hi, is it possible to retrieve a small sample of the train.mat file included in that archive? I am looking to train my own (much smaller) dataset and do not have enough physical memory to load the example. Thanks!
