### ISSUE TITLE
[Question] Can DanQ identify motifs that are separated by spacer sequence? 

### ISSUE THREAD

**Issue by jolespin** [uci-cbcl/DanQ#10]
Have you tested the ability for DanQ to identify motif sequences that are separater by a spacer sequence?  For example, if `kernel_size=26` in `Conv1D` and there was a motif (`motif_A`) of 8 bp separated by a 10 bp sequence and then another motif (`motif_B`) of 8 bp.  Would it be able to detect it with unspecific probabilities in the middle 10 bp region?  Just curious if it can handle split motifs.

**Comment by daquang** [comment]
DanQ is not specifically designed to capture spacer motifs. Theoretically, you could have motifs like the one you described, but there's no way that rule can be enforced. How familiar are you with convolutional kernels and position weight matrices? The basic mathematics of those two should make it clear what is possible to learn.

**Comment by jolespin** [comment]
I think it could only work if there were a lot of sequences that had highly conserved motifs separated by a spacer.  Thanks for your response.
