### ISSUE TITLE
A question about your paper.

### ISSUE THREAD

**Issue by ljw-struggle** [uci-cbcl/DanQ#14]
you said the predicted probability for each sequence was computed as the average
of the probability predictions for the forward and reverse complement sequence pairs, similar to DeepSEA’s evaluation experiments. But I can't find you do it in your code.  It seems that you only predict the probabilities through the forward sequence.

**Comment by daquang** [comment]
In the training and test sequences, the first half sequences (I think this numbers about 2 million) are forward sequences. The reverse complement sequences are the second half, in the same exact order as the first half. You can simply average predictions from the first and second half.

**Comment by ljw-struggle** [comment]
> In the training and test sequences, the first half sequences (I think this numbers about 2 million) are forward sequences. The reverse complement sequences are the second half, in the same exact order as the first half. You can simply average predictions from the first and second half

How to get the complement sequences? what is the order of the ACGT? And whether the AUROC and AUPR is based on the average probabilities of forward and complement sequence?

**Comment by ljw-struggle** [comment]
> In the training and test sequences, the first half sequences (I think this numbers about 2 million) are forward sequences. The reverse complement sequences are the second half, in the same exact order as the first half. You can simply average predictions from the first and second half.

You are so responsive. RESPECT !!!!!

**Comment by daquang** [comment]
The nucleotides are in the order of AGCT. I believe the tensors are of the shape: num_samples, sequence_length, num_nucleotides. For example, if you had 1,000,000 forward sequences, the tensor will be of shape 2,000,000 x 1,000 x 4 (remember to double samples for reverse complement). You can grab the forward sequences with NumPy indexing:

x[0:1000000, :, :]

and you can grab the reverse complement sequences by grabbing the second half as follows:

x[1000000:2000000, :, :]

The AUROC and AUPR are based on the average probabilities of forward and reverse sequences.
