### ISSUE TITLE
AUC Class Ordering

### ISSUE THREAD

**Issue by minhoolee** [uci-cbcl/DanQ#4]
Hi,

Could you provide the code used to generate the ROC and PR AUC curves in aucs.txt? How do you map the class prediction results (919) to the alphabetically ordered list of cell type names that are in aucs.txt? 

Also, do you happen to have the code that DeepSEA used for preprocessing to get the train, valid, and test mats? A request for that code in their repository has not been responded to.

Thanks in advance.

**Comment by daquang** [comment]
Assuming you already have the model and data loaded properly, you can try something like this:

import numpy as np
import scipy.io

testmat = loadmat('test.mat')
X, y = np.transpose(testmat['testxdata'],axes=(0,2,1)), testmat['testdata']

test_predicts = model.predict(X)


The variable test_predicts is a (455024, 919) matrix, with each column corresponding to the chromatin marks in the same order as found in http://deepsea.princeton.edu/media/help/aucs.txt. In this particular case, we have 455024, which is actually 227512 forward and 227512 reverse sequences. For example, if you wanted to calculate the ROC AUC of the first chromatin mark, 8988T	DNase, do the following:

from sklearn.metrics import roc_auc_score
roc_auc_8988T_DNase = roc_auc_score(y[:,0], test_predicts[:,0])

I do not have the original source code for preprocessing. I have asked the authors if they could provide it, but they have not. However, if you have bedtools, it should be straightforward from reading the DeepSEA paper what you should do.
