### ISSUE TITLE
Link to Supplementary Data missing

### ISSUE THREAD

**Issue by kauralasoo** [uci-cbcl/DanQ#5]
The link to Supplementary Data on the journal website (https://academic.oup.com/nar/article-lookup/doi/10.1093/nar/gkw226#42670419) does not work. Would you be able to contact the journal to get this fixed?

**Comment by daquang** [comment]
I'll contact them! In the meantime, here's a PDF of the supplementary text. Let me know if it doesn't work:

https://www.dropbox.com/s/j365ww6y5m3cmi7/Supplementary.pdf?dl=0

**Comment by kauralasoo** [comment]
Thanks!
