### ISSUE TITLE
One hot matrix

### ISSUE THREAD

**Issue by logust79** [uci-cbcl/DanQ#6]
Hello,
I'm not very clear on how the one-hot matrix is coded. In your paper Figure 1, it appears to be A,C,G,T, but in the first section (Features and data) under Materials and methods, it writes A,G,C,T. Which is the right way to read the matrix?

Kind regards,
Jing

**Comment by daquang** [comment]
Sorry for the confusion. I drew it as A,C,G,T because that's my personal preference. The DeepSEA authors  made the data with the order A,G,C,T, which is the right way to read the matrix.
