### ISSUE TITLE
Crash when compiling

### ISSUE THREAD

**Issue by ATCGCGCTC** [uci-cbcl/DanQ#7]
Hey Daniel,

I am trying to compile your model so I can use it as a pre-trained model.  However I am running into an error when using keras 0.2.0, your version of seya and theano 0.8.0 (0.7.0 and 0.9.0 did not work) and all other provided versions of packages. In the description you wrote that you might be switching to tensorflow and later versions of keras. Do you happen to have a new version of your model that's more easily portable? Thanks in advance.

**Comment by daquang** [comment]
This package is pretty outdated I admit. I could switch over to newer versions, but I would have to train new networks again. Training would likely take up to two weeks to complete. At the moment, I am busy with my thesis defense and moving to my new postdoc position, so the earliest I can work on this is sometime in August or September. Porting the code isn't the hard part, it's the training that will take a while. Let me know how you would like to proceed.

**Comment by ATCGCGCTC** [comment]
If you could find the time to retrain the model that'd be amazing!

**Comment by daquang** [comment]
Then I will do it! Expect updates in the future! :)
